# Generated by Django 3.0.8 on 2020-07-17 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated at')),
                ('user_url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('url_hash', models.CharField(max_length=200, unique=True, verbose_name='Hash URL')),
            ],
            options={
                'verbose_name': 'url store',
                'verbose_name_plural': 'urls store',
                'db_table': 'url store',
            },
        ),
    ]
