# Generated by Django 3.0.8 on 2020-07-13 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated at')),
                ('user_url', models.URLField(max_length=1000, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid URL', regex='(https?:\\/\\/(?:www\\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|www\\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|https?:\\/\\/(?:www\\.|(?!www))[a-zA-Z0-9]+\\.[^\\s]{2,}|www\\.[a-zA-Z0-9]+\\.[^\\s]{2,})')], verbose_name='URL')),
                ('url_hash', models.URLField(unique=True, verbose_name='Hash URL')),
            ],
            options={
                'verbose_name': 'url',
                'verbose_name_plural': 'urls',
                'db_table': 'url',
            },
        ),
    ]
